name: xction.co.kr Deploy

on:
    push:
        branches:
            - feature/CodeDeploy

jobs:
    build:
        
        runs-on: ubuntu-latest

        steps:
        - name: feat/CodeDeploy 브랜치 체크아웃
          uses: actions/checkout@v2
          with:
            ref: feature/CodeDeploy

        - name: yarn 설치
          run: yarn install

        - name: yarn 빌드
          run: yarn build

        - name: AWS 설정
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        
        - name: S3 버킷에 빌드파일 업로드
          run: aws s3 sync ./build s3://xction.co.kr --delete

        - name: CodeDeploy 배포
          run: aws deploy create-deployment --application-name xction.co.kr --deployment-group-name xction.co.kr-deploy --s3-location bucket=xction.co.kr,bundleType=zip,key=build.zip
